global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api_gateway"
    static_configs:
      - targets: [ "api_gateway:4000" ]

  - job_name: "idp_service"
    static_configs:
      - targets: [ "idp_service:5000" ]

  - job_name: "evaluation_service"
    static_configs:
    - targets: [ "evaluation_service:6000" ]
  - job_name: "rabbitmq"
    static_configs:
    -targets: [ "rabbitmq:15672" ]

  -job_name: "prometheus"
    static_configs:
    -targets: [ "localhost:9090" ]

  -job_name: "jaeger"
    static_configs:
    -targets: [ "jaeger:16686" ]